### ISSUE TITLE
Exclude entry from unimported results

### ISSUE THREAD

**Issue by olidacombe** [smeijer/unimported#11] opened 2020-10-09 16:43 UTC
When I run unimported, the entry file is being reported as unimported, which is true because it's the top-level source file, but shouldn't it be excluded from being reported as unimported?

E.g.

```
// .unimportedrc.json
{
	"entry": ["index.js"]
}
```

```
// index.js
import bla from './bla'
```

```
// bla.js
export default 1
```

```
npx: installed 195 in 11.958s

       summary               unimported v1.5.0
─────────────────────────────────────────────────────────────────────────────────────────────────────────
       entry file          : 

       unresolved imports  : 0
       unused dependencies : 0
       unimported files    : 1


─────┬───────────────────────────────────────────────────────────────────────────────────────────────────
     │ 1 unimported files
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ index.js
─────┴───────────────────────────────────────────────────────────────────────────────────────────────────


       Inspect the results and run npx unimported -u to update ignore lists
```

**Comment by smeijer** [comment] 2020-10-09 16:55
It looks like the entry file isn't recognized. Does it help if you use a relative file path?

```
// .unimportedrc.json
{
	"entry": ["./index.js"]
} 
```

**Comment by olidacombe** [comment] 2020-10-09 17:31
> It looks like the entry file isn't recognized. Does it help if you use a relative file path?
> 
> ```
> // .unimportedrc.json
> {
> 	"entry": ["./index.js"]
> } 
> ```

Thanks, I just gave this a go, but received exactly the same result.  The absence of text in the `entry file :` line of the report I think is another issue.  When I remove the import line from `index.js`, I see `bla.js` added to the list of unimported source files so `unimported` is clearly functioning.

**Comment by preston-wagner** [comment] 2021-02-27 00:58
Bumping this, I'm on version 1.5.0 and having the same issue.

**Comment by smeijer** [comment] 2021-02-27 09:01
@preston-wagner do you have a repo at which I can take look?

**Comment by smeijer** [comment] 2021-02-27 10:11
You may forget about the repo. I'm able to reproduce. I'll be working on a fix.

**Comment by smeijer** [comment] 2021-02-27 10:35
Should be fixed now.

**Closed by smeijer** 2021-02-27 10:35 UTC
