### ISSUE TITLE
All files unimported

### ISSUE THREAD

**Issue by systemallica** [smeijer/unimported#71] opened 2022-01-29 19:41 UTC
I'm trying to run `unimported` on a React w/ typescript project. And when running `npx unimported --no-cache` all the project files are listed as not used. I have read the [other](https://github.com/smeijer/unimported/issues/59) [issues](https://github.com/smeijer/unimported/issues/64) but the solutions there didn't help in my case.

Running `npx unimported --show-config` gives the following:

```
{
  version: '1.19.1',
  preset: 'node',
  flow: false,
  rootDir: './src',
  ignoreUnresolved: [],
  ignoreUnimported: [],
  ignoreUnused: [],
  ignorePatterns: [
    '**/node_modules/**',
    '**/*.tests.{js,jsx,ts,tsx}',
    '**/*.test.{js,jsx,ts,tsx}',
    '**/*.spec.{js,jsx,ts,tsx}',
    '**/tests/**',
    '**/__tests__/**',
    '**/*.d.ts'
  ],
  moduleDirectory: undefined,
  entryFiles: [
    {
      file: 'src/index.tsx',
      aliases: {},
      extensions: [ '.js', '.jsx', '.ts', '.tsx' ]
    }
  ],
  extensions: [ '.js', '.jsx', '.ts', '.tsx' ]
}
```

```
       summary               unimported v1.19.1 (node)

       entry file          : src/index.tsx

       unresolved imports  : 49
       unused dependencies : 27
       unimported files    : 402
```

Any clue?

**Comment by riverliway** [comment] 2022-04-16 17:14
I have the same problem. It finds `index.tsx` and all of the imports from that file, but it fails to resolve all of the imports 2 levels deep or more. My project structure looks like this, with the `index.tsx` file, the `components` directory, and the `utils` directory inside a `src` directory. The config and `package.json` are next to the `src` folder.

```
src
|-- index.tsx
|-- components
|   |-- directory
|   |   |-- component.tsx
|   |   `-- ...
|   `-- ...
`-- utils
    |-- util.ts
    `-- ...
```

My import statements all look like:
```
import component from 'components/directory/component'
import subcomponent from './subdirectory/subcomponent'
import util from 'utils/util.ts'
```
using both absolute and relative imports.

My `index.tsx` imports the app component from `components/App/App.tsx` which this package can find, but it is unable to resolve any imports from there such as `components/SignIn/SignIn.tsx` (inside App). 

I tried making SignIn a relative import `../SignIn/SignIn` in which this package was now able to resolve SignIn, but failed to resolve all of SignIn's imports (both absolute and relative).

I tried various config changes like making rootDir `./src` and adding an alias for `components => src/components`, but neither fixed the issue.

**Comment by smeijer** [comment] 2022-05-02 09:43
What you're experiencing is most certainly a configuration issue related to the aliases. I can't give you the exact configuration, without having a repo to look at. If you're able to, please share a reproduction. Otherwise, I can only ask you to fiddle around with the aliases to make it work.

I'm closing this issue as it's not a bug in this project. But please keep the discussion going if you have any questions.

**Closed by smeijer** 2022-05-02 09:43 UTC
Labels: question
