### ISSUE TITLE
How to find unimported images?

### ISSUE THREAD

**Issue by timsofteng** [smeijer/unimported#132] opened 2023-01-29 16:42 UTC
Hello. We add unimported js into our project and it works pretty well.
There are a lot of unused images in common src/assets location in our project. However `unimported` doesn't mark them.
How to find unimported images?

**Comment by smeijer** [comment] 2023-03-02 18:27
We don't support non-code files at the moment.

**Comment by smeijer** [comment] 2023-03-02 18:28
Closing as duplicate of #103

**Closed by smeijer** 2023-03-02 18:28 UTC
Labels: feature
